export enum Selector {
  SEARCH_INPUT = 'input[type="search"]',
  ROLE_LISTBOX = '[role="listbox"]',
  ROLE_OPTION = '[role="option"]',
  JOB_TEMPLATE_ID = '#job',
  KEYWORDS_TEMPLATE_ID = '#keywords',
  PROJECT_TEMPLATE_ID = '#project',
  PROJECT_HOLDER = '.project-holder',
  PROJECT_IMAGE = '.image-container img',
  PROJECT_INFO_ICON = '.info-icons .info',
  PROJECT_LINK_ICON = '.info-icons .link',
  PROJECT = '.proj',
  PROJECT_TITLE = '.proj h5.title',
  JOB_HOLDER = '.job-holder',
  NAVIGATION_LINK = 'nav a',
}
